<?php
/**
 * @var \Gzhegow\Front\FrontTemplateContract $this
 */

/** @see /tests/disc/html/modals/demo/layout.modal.phtml */
$this->layout('@html::modals/demo/layout.modal', [
    'id' => 'success',
]);

?>


<?php $this->sectionStart('modal-title'); ?>

    <div>Всё отлично!</div>

<?php $this->sectionEnd(); ?>


<?php $this->sectionStart('modal-content'); ?>

    <div>
        <div>
            Форма была отправлена.
        </div>
        <div>
            Скоро наши специалисты Вам перезвонят
        </div>
    </div>

<?php $this->sectionEnd(); ?>
